### ISSUE TITLE
how can we get inputs and outputs from our python script

### ISSUE THREAD

**Issue by IntrinsicInnovation** [SafeBreach-Labs/CloudMiner#2]
Could you please tell me how I can print out or output something to show my uploaded python script actually was successful?

Thanks!

**Comment by arielgamrian** [comment]
Hi @IntrinsicInnovation. There are 2 solutions for this:
1. Send the output to your own server. 
2. Raise an exception to contain your output. This can be later viewed as part of the upload status.

**Comment by IntrinsicInnovation** [comment]
Thanks for that.  Also, is there an actual crypto mining python script that works with it?  (new to python here.)

**Comment by arielgamrian** [comment]
@IntrinsicInnovation Iv’e never tried to execute a real miner as its against Azure license.
