### ISSUE TITLE
communicate back to azure cli?

### ISSUE THREAD

**Issue by IntrinsicInnovation** [SafeBreach-Labs/CloudMiner#5]
How would I communicate back through the cli to the command line to at least show that my script ran or failed or did something?  I tried what you suggested, by raising an exception but nothing works, as I get no output, and cant write to the server:  Could you give me a sample script that can be included in cloudminer that actually sends output back to the command line or anywhere where I could read it?

Thanks again!

**Comment by arielgamrian** [comment]
@IntrinsicInnovation 
There's no easy way to get your output to the command line but:
As I said earlier, you have 2 methods to validate your script was actually executed. Attaching an example to get both validations within a single script. This script was tested today by me.
[test.txt](https://github.com/SafeBreach-Labs/CloudMiner/files/14568171/test.txt)

The image below is an example of what you see pressing the uploaded package.
![image](https://github.com/SafeBreach-Labs/CloudMiner/assets/16081640/ededa410-16e4-4e1e-b4d6-34dc4f5bd963)

Let me know if further information is needed :)

**Comment by IntrinsicInnovation** [comment]
Hi, thanks but I still get the exact same thing again, I tried your test.txt file:  
<img width="1005" alt="screenshot1" src="https://github.com/SafeBreach-Labs/CloudMiner/assets/7356836/604fa8c7-44e2-4a3d-ade0-6be1ce308eec">

**Comment by IntrinsicInnovation** [comment]
maybe permissions in the actual azure account?  it seems to do absolutely nothing, but no error, no hint, nothing to indicate anything failed or did nothing

**Comment by arielgamrian** [comment]
@IntrinsicInnovation Are you listening on a server to receive the script request? If not - remove this line (requests.post) and only raise exception. You should later see it in the Automation Account python packages.
![image](https://github.com/SafeBreach-Labs/CloudMiner/assets/16081640/50aca351-0316-4e41-a934-d1b65f19e2b2)

**Comment by IntrinsicInnovation** [comment]
Ok, thanks very much.  I'll try that.  I did notice a few failed statuses from yesterday.  I also keep getting the error:  
 raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

Is that like an automatic ip block or manual block by an admin?  It was working a few days ago.

**Comment by IntrinsicInnovation** [comment]
ok, got it to work:  
![image](https://github.com/SafeBreach-Labs/CloudMiner/assets/7356836/fa2462e8-1906-4401-9468-0ba31f456387)

Thanks man.  I guess the only thing is the ip blocking error, or whatever is happening there.  I can just switch IP's and get it to work, but a bit of a hassle.
