### ISSUE TITLE
Is it still working? 

### ISSUE THREAD

**Issue by vansh712** [SafeBreach-Labs/CloudMiner#6]
Does this still work to date?

**Comment by arielgamrian** [comment]
Yes

**Comment by vansh712** [comment]
Is there any tutorial or something explaining how to set it up?

**Comment by arielgamrian** [comment]
Just open an Azure account and create an Automation Account. After these are done, you can easily use the tool.
https://learn.microsoft.com/en-us/azure/automation/quickstarts/create-azure-automation-account-portal?source=recommendations

Let me know if further information is needed.

**Comment by vansh712** [comment]
Sorry for asking way too many questions but where do I add the pool and my own address? Also which coin is it mining?

**Comment by arielgamrian** [comment]
@vansh712 That's fine :)
CloudMiner does not mine crypto. It provides a platform for executing YOUR OWN code within Azure with no charges.
